### ISSUE TITLE
REPL crashes while typing

### ISSUE THREAD

**Issue by eshyong** [bpython/bpython#610]
I was using bpython today to work on some kaggle competition problems when it suddenly crashed in the middle of typing. Here's a stack trace:

```
>>> num_men_survived = np.sum(data_array[men_only_stats, 1]. <- exception occurs here
Traceback (most recent call last):
  File "/usr/local/bin/bpython", line 9, in <module>
    load_entry_point('bpython==0.14.2', 'console_scripts', 'bpython')()
  File "/usr/local/lib/python3.4/site-packages/bpython/curtsies.py", line 79, in main
    interactive=(not exec_args))
  File "/usr/local/lib/python3.4/site-packages/bpython/curtsies.py", line 177, in mainloop
    process_event(e)
  File "/usr/local/lib/python3.4/site-packages/bpython/curtsies.py", line 135, in process_event
    repl.process_event(e)
  File "/usr/local/lib/python3.4/site-packages/bpython/curtsiesfrontend/repl.py", line 488, in process_event
    return self.process_key_event(e)
  File "/usr/local/lib/python3.4/site-packages/bpython/curtsiesfrontend/repl.py", line 629, in process_key_event
    self.add_normal_character(e)
  File "/usr/local/lib/python3.4/site-packages/bpython/curtsiesfrontend/repl.py", line 848, in add_normal_character
    self.cursor_offset += 1
  File "/usr/local/lib/python3.4/site-packages/bpython/curtsiesfrontend/repl.py", line 1345, in _set_cursor_offset
    self.update_completion()
  File "/usr/local/lib/python3.4/site-packages/bpython/curtsiesfrontend/repl.py", line 878, in update_completion
    self.list_win_visible = BpythonRepl.complete(self, tab)
  File "/usr/local/lib/python3.4/site-packages/bpython/repl.py", line 608, in complete
    self.current_line, matches, completer)
  File "/usr/local/lib/python3.4/site-packages/bpython/repl.py", line 278, in update
    self.orig_cursor_offset, self.orig_line)
TypeError: 'NoneType' object is not iterable
```

This is bpython version 0.14.2 running on Python 3.4.2, on OSX El Capitan 10.11.3.

Unfortunately, that's the only context I currently have. If anyone has suggestions on where to start digging, I'd be happy to report back once I've gathered more info!

**Comment by thomasballinger** [comment]
I'm having trouble finding a bug for this, but I can reproduce this in 0.14.2 but not in 0.15. If you can install the newest version of bpython that should fix the issue, but it would be nice to find what we fixed.

**Comment by thomasballinger** [comment]
I think this was only fixed because I messed with the autocompleter priority. This is going on the list to take a look at soon.

* More reasonable logging - debug level completer crashes are hard to pull out from the many other debug messages
* Parameter name completion seems broken (this bug)
* The default completer isn't continuing past global variable completion when it returns no matches

**Comment by eshyong** [comment]
Gotcha, will update bpython. I'll let you know if I still see it after that. Thanks!

**Comment by rsalmei** [comment]
Hello @thomasballinger,
I have a very similar stacktrace, maybe it could help... The crash occurs when we press '(' on a lambda parameter:

```
bpython version 0.14.2 on top of Python 2.7.11 /usr/local/opt/python/bin/python2.7
>>> def func(p=lambda x:x):
...     return p
Traceback (most recent call last):
  File "/usr/local/bin/bpython", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 79, in main
    interactive=(not exec_args))
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 177, in mainloop
    process_event(e)
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsies.py", line 135, in process_event
    repl.process_event(e)
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 488, in process_event
    return self.process_key_event(e)
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 629, in process_key_event
    self.add_normal_character(e)
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 848, in add_normal_character
    self.cursor_offset += 1
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 1345, in _set_cursor_offset
    self.update_completion()
  File "/usr/local/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 878, in update_completion
    self.list_win_visible = BpythonRepl.complete(self, tab)
  File "/usr/local/lib/python2.7/site-packages/bpython/repl.py", line 599, in complete
    history=self.history)
  File "/usr/local/lib/python2.7/site-packages/bpython/autocomplete.py", line 466, in get_completer_bpython
    return get_completer(BPYTHON_COMPLETER, cursor_offset, line, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/bpython/autocomplete.py", line 446, in get_completer
    cursor_offset, line, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/bpython/autocomplete.py", line 421, in matches
    history=history)
  File "/usr/local/lib/python2.7/site-packages/bpython/autocomplete.py", line 376, in matches
    completions = script.completions()
  File "/usr/local/lib/python2.7/site-packages/jedi/api/__init__.py", line 197, in completions
    for p in call_sig.params:
  File "/usr/local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/jedi/api/classes.py", line 348, in params
    sub = followed.get_subscope_by_name('__init__')
  File "/usr/local/lib/python2.7/site-packages/jedi/evaluate/representation.py", line 563, in __getattr__
    return getattr(self.base_func, name)
AttributeError: 'Lambda' object has no attribute 'get_subscope_by_name'
```

**Comment by thomasballinger** [comment]
@rsalmei I believe this one is properly fixed in bpython 0.15, we're much more careful with trusting Jedi not to crash ;)

**Comment by sebastinas** [comment]
Yes, that should be fixed in 0.15.
